include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false
    prefer_final_locals: false
    prefer_final_fields: false
    prefer_generic_function_type_aliases: false
    prefer_is_empty: false
    prefer_is_not_empty: false
    prefer_is_not_operator: false
    prefer_null_aware_operators: false
    prefer_relative_eq: false
    prefer_void_to_null: false
    remove_unnecessary_casts: false
    remove_unnecessary_const: false
    remove_unnecessary_string_interpolations: false
    type_annotate_public_apis: false