name: education
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  audioplayers: ^0.20.1
  intl: ^0.17.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  google_fonts: 4.0.4
  http: ^0.13.6
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_riverpod: ^1.0.4
  provider: ^6.1.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true