name: CI/CD Pipeline

on:
  push:
    branches:
      - lab7
  pull_request:
    branches:
      - lab7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: stable
          architecture: X64
          cache: false
          pub-cache-path: default

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test test/widget_test.dart

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: stable
          architecture: X64
          cache: false
          pub-cache-path: default

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: stable
          architecture: X64
          cache: false
          pub-cache-path: default

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Deploy to GitHub Pages
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /https://github.com/Woolfer0097/Sum24FlutterCourse
          customArgs: "lib/templates/lab7/main.dart"

